/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "tren.h"

int
main (int argc, char *argv[])
{
	int i,j;
	CLIENT *cl;
	char *host;
	respuesta *resultado;
	par asiento;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cl = clnt_create(host, TREN_PROG, TREN_VERS, "tcp");

	asiento[0] = 0;
	asiento[1] = 0;
	if (cl == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	resultado = reservar_1(asiento, cl);
	for (i = 0; i < 10; ++i)
	{
		for (j = 0; j < 4; ++j)
		{
			printf( "%c ", resultado->disponibles[i*10+j] );
		}
		printf("\n");
	}



exit (0);
}
