/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tren.h"

respuesta *
reservar_1_svc(int *argp, struct svc_req *rqstp)
{
	int i,j;
	static respuesta  result;
	static int vagon [10][4];





	result.codigo = 1;
	for (i = 0; i < 10; ++i)
		for (j = 0; j < 4; ++j)
			result.disponibles[i*10+j] = vagon[i][j] ? 'X' : '0'; 


	return &result;
}
