/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tren.h"

bool_t
xdr_par (XDR *xdrs, par objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_respuesta (XDR *xdrs, respuesta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigo))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->disponibles, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
