/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "tren.h"

int
main (int argc, char *argv[])
{
	int i,j;
	CLIENT *cl;
	char *host;
	respuesta *resultado;
	par asiento;

	if (argc < 4) {
		printf ("Uso: %s ip_servidor -f fila -c columna\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cl = clnt_create(host, TREN_PROG, TREN_VERS, "tcp");

	asiento[0] = atoi(argv[2]);
	asiento[1] = atoi(argv[3]);
	if (cl == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	resultado = reservar_1(asiento, cl);
	if (!resultado->codigo)
	{
		printf("El puesto ha sido reservado exitosamente.\n");
	} else if (resultado->codigo == 1)
	{
		for (i = 0; i < 10; ++i)
		{
			for (j = 0; j < 4; ++j)
			{
				printf( "%c ", resultado->disponibles[i*4+j] );
			}
			printf("\n");
		}
	} else if (resultado->codigo == 2)
	{
		printf("El tren está lleno.\n");
	} else {
		printf("Mensaje corrupto.\n");
		exit(1);
	}
exit (0);
}
